[workspace]
resolver = "2"
members = [
    "crates/*",
]
default-members = [
    "crates/phodopus",
    "crates/phodopus-util",
]

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["kyren <catherine@kyju.org>", "The Bitty Terminal Developers"]
license = "MIT OR CC0-1.0"
repository = "https://github.com/bitty-terminal/phodopus"

[workspace.dependencies]
ahash = "0.8"
allocator-api2 = "0.2"
anyhow = "1.0"
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "5a7534b883b703f23cfb8c3cfdf033460aa77ea9", features = ["allocator-api2", "hashbrown"] }
hashbrown = { version = "0.14", features = ["raw"] }
rand = { version = "0.9", features = ["small_rng"] }
serde = "1.0"
thiserror = "2.0"

phodopus = { path = "crates/phodopus", version = "0.1.0-alpha.1" }
phodopus-util = { path = "crates/phodopus-util", version = "0.1.0-alpha.1" }
